name: structbioinfo
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.12
  - numpy=1.23.5
  - scipy=1.11.3
  - pandas=1.5.3
  - matplotlib=3.7.1
  - biopandas=0.4.1
  - pypdb=2.3
  - tqdm=4.66.1
  - py3dmol=2.0.4
  - jupyter
  - openmm
  - nglview
  - mdtraj
  - mdanalysis
  - pdbfixer
  - rdkit
